---
title: "Homework 03"
---

## Homework 03 - due 10/04/2017

Using the HELP dataset:

* create "Table 1"
* provide the summary stats for the baseline data - overall and by randomization group (Usual Care versus the HELP Clinic)
* determine whether you want to provide parametric or non-parametric stats - based on your determination of normality assumptions, sample size considerations, appropriateness of the statistical test and communication with your audience.
* include the appropriate statistical test comparing the group measurements and subject characteristics at baseline
* write a statistical methods section describing (and explaining to your readers) the methods you used to create Table 1 and why you choose those methods to make the comparisons between the groups
* write 1-2 paragraphs (as the beginning of a results section) describing the sample overall at baseline and by group (use the data you presented in Table 1 to help you).

## Report Template for Homework 03

See the WORD document template `N736Homework03_Template.docx` you can download from [https://github.com/melindahiggins2000/N736Fall2017/blob/master/N736Homework03_Template.docx](https://github.com/melindahiggins2000/N736Fall2017/blob/master/N736Homework03_Template.docx) - click "Download".


